channel_sources:
  - robotraconteur,wasontech,conda-forge,defaults
channel_targets:
  - robotraconteur main
macos_min_version:             # [osx]
  - 10.14                      # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.14                      # [osx]