package:
  name: robotraconteur_training_sim
  version: 0.4.0

source:
  git_url: https://github.com/johnwason/robotraconteur_training_sim.git
  git_rev: 10341a394d2f46838d28f156c85ac8931ace972b

requirements:
  host:
    - robotraconteur
    - robotraconteur_companion
    - gazebo
    - gazebo_robotraconteur_server_plugin
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv
    - robotraconteur_companion_python
    - python

  run:
    - robotraconteur
    - robotraconteur_companion
    - gazebo
    - gazebo_robotraconteur_server_plugin
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv
    - qpsolvers
    - robotraconteur_companion_python
    - python
    - drekar-launch
    - drekar-launch-process
    - menuinst # [win]

build:
  number: 0

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: "Gazebo based training simulator for Robot Raconteur"