package:
  name: robotraconteur_training_sim
  version: 0.1.4a

source:
  git_url: https://github.com/robotraconteur-contrib/robotraconteur_training_sim.git
  git_depth: 10
  git_rev: v0.1.4

requirements:
  host:
    - robotraconteur
    - robotraconteur_companion
    - gazebo
    - gazebo_robotraconteur_server_plugin
    - gazebo_model_robotraconteur_driver
    - pyyaml
    - py-opencv
    - robotraconteur_companion_python

  run:
    - robotraconteur
    - robotraconteur_companion
    - gazebo
    - gazebo_robotraconteur_server_plugin
    - gazebo_model_robotraconteur_driver
    - pyyaml
    - py-opencv
    - qpsolvers
    - robotraconteur_companion_python

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: "Gazebo based training simulator for Robot Raconteur"