package:
  name: robotraconteur_training_sim
  version: 0.3.0

source:
  git_url: https://github.com/robotraconteur-contrib/robotraconteur_training_sim.git
  git_rev: d8ae6291670086d1d1563a2679a8639454e163ae

requirements:
  host:
    - robotraconteur
    - robotraconteur_companion
    - gazebo
    - gazebo_robotraconteur_server_plugin
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv=4.7.0
    - robotraconteur_companion_python
    - python

  run:
    - robotraconteur
    - robotraconteur_companion
    - gazebo
    - gazebo_robotraconteur_server_plugin
    - gazebo-robotraconteur-sim-drivers
    - pyyaml
    - py-opencv=4.7.0
    - qpsolvers
    - robotraconteur_companion_python
    - python
    - drekar-launch
    - drekar-launch-process

build:
  number: 0

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: "Gazebo based training simulator for Robot Raconteur"